---
- name: Install assorted software dependencies
  yum:
    name: 
      - gcc
      - dkms
      - make
      - qt
      - libgomp
      - patch
      - wget
      - kernel-devel
      - kernel-headers
      - binutils
      - glibc-headers
      - glibc-devel
    state: latest
  become: yes
  become_method: su


############ VirtualBox Installation (Move to separate role later) ###############

- name: Download Virtual Box
  shell:
    "wget https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo -P /etc/yum.repos.d"
  become: yes
  become_method: su

- name: Install Virtual Box
  yum:
    name: VirtualBox-6.1
    state: latest
  become: yes
  become_method: su



